return {
  dap = {
    BreakpointCondition = { " ", "DiagnosticError" },
    Breakpoint = { " ", "DiagnosticError" },
    BreakpointRejected = { " ", "DiagnosticError" },
    LogPoint = { "✪ ", "DiagnosticError" },
    Stopped = { " ", "DiagnosticWarn", "DapStoppedLine" },
  },
  git = {
    Add = " ",
    Branch = " ",
    Conflict = " ",
    Diff = " ",
    Git = "󰊢 ",
    Ignore = " ",
    Mod = " ",
    Octoface = " ",
    Remove = " ",
    Rename = " ",
    Repo = " ",
    Stage = " ",
    Unmerge = " ",
    Unstage = " ",
    Untrack = "󰞋 ",
  },
  kind_icons = {
    Array = " ",
    Boolean = " ",
    Class = " ",
    Color = " ",
    Constant = " ",
    Constructor = " ",
    Enum = " ",
    EnumMember = " ",
    Event = " ",
    Field = " ",
    File = " ",
    Folder = "󰉋 ",
    Function = " ",
    Interface = " ",
    Key = " ",
    Keyword = " ",
    Method = " ",
    Module = " ",
    Namespace = " ",
    Null = "󰟢 ",
    Number = " ",
    Object = " ",
    Operator = " ",
    Package = " ",
    Property = " ",
    Reference = " ",
    Snippet = " ",
    String = " ",
    Struct = " ",
    Text = " ",
    TypeParameter = " ",
    Unit = " ",
    Value = " ",
    Variable = " ",
  },
  diagnostics = {
    Error = " ",
    Hint = "󰌵",
    Info = " ",
    Warn = " ",
  },
  ui = {
    Search = " ",
    Recent = " ",
  },
}
